"""Add is_confirmed column to users

Revision ID: f836e9d30c71
Revises: b2ae0f0dbf62
Create Date: 2025-10-29 00:54:02.674849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f836e9d30c71'
down_revision: Union[str, Sequence[str], None] = 'b2ae0f0dbf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
